runners:
  - name: do-runner
    # Cloud Provider: DigitalOcean
    cloud: digitalocean
    # Cheapest VM on DigitalOcean
    instance_type: s-1vcpu-1gb
    # Ubuntu-20.4  image"
    machine_image: ubuntu-20-04-x64
    # Path of the relevant workflow file
    workflow: .github/workflows/test.yml
    # Number of runners to provision on every trigger on Actions job
    # 3 because testing on Python 3.7, 3.8
    # See .github/workflows/build-gpu.yml
    count: 1
